branch-defaults:
  default:
    environment: udagram-api-dev-hieunt114
    group_suffix: null
deploy:
  artifact: ./Archive.zip
environment-defaults:
  udagram-api-dev-hieunt114:
    branch: null
    repository: null
  udagram-api-dev-hieunt114:
    branch: null
    repository: null
global:
  application_name: udagram-api-hieunt114
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
