branch-defaults:
  default:
    environment: udagram-api-dev-hieunt114
environment-defaults:
  udagram-api-dev-hieunt114:
    branch: null
    repository: null
global:
  application_name: udagram-api-hieunt114
  default_ec2_keyname: null
  default_platform: Node.js 14
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
