branch-defaults:
  default:
    environment: Udagram-env
    group_suffix: null
  main:
    environment: udagram-hieunt114-api-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
environment-defaults:
  Udagram-env:
    branch: null
    repository: null
  udagram-hieunt114-api-dev:
    branch: null
    repository: null
global:
  application_name: udagram-hieunt114-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
